# Generated by Django 5.2 on 2025-04-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
