# Generated by Django 5.2 on 2025-04-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='usuario',
        ),
    ]
