# Generated by Django 5.2 on 2025-04-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_categoriaservicio_servicio_tipo_subcategoriaservicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
