# Generated by Django 5.2 on 2025-04-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_remove_consulta_servicio_remove_consulta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.categoriaservicio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='email',
            field=models.EmailField(default='ejemplo@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
