# Generated by Django 5.2 on 2025-04-24 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_remove_servicio_subcategoria_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='servicio',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spa.subcategoriaservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
