# Generated by Django 5.2 on 2025-04-19 03:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_subcategoriaservicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='email',
            field=models.EmailField(default='anon@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa.subcategoria'),
        ),
    ]
