# Generated by Django 5.2 on 2025-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_subcategoria_remove_consulta_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
