# Generated by Django 5.2 on 2025-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_alter_servicio_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
