# Generated by Django 5.2 on 2025-04-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_remove_consulta_servicio_alter_consulta_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha_envio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.servicio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
