# Generated by Django 5.2 on 2025-04-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_alter_servicio_nombre_alter_servicio_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='email',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.servicio'),
        ),
    ]
