# Generated by Django 5.1.1 on 2025-06-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='spa.profesional'),
        ),
    ]
