# Generated by Django 5.2.3 on 2025-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_turno_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentarios sobre el turno', null=True),
        ),
    ]
