# Generated by Django 5.1.1 on 2025-06-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0011_turno_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.profesional'),
        ),
    ]
