# Generated by Django 5.2.3 on 2025-06-17 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0012_cartitem_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='spa.servicio'),
        ),
    ]
